/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as CasesCaseIdEpisodesEpisodeIdRouteImport } from './routes/cases.$caseId.episodes.$episodeId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdEpisodesEpisodeIdRoute =
  CasesCaseIdEpisodesEpisodeIdRouteImport.update({
    id: '/episodes/$episodeId',
    path: '/episodes/$episodeId',
    getParentRoute: () => CasesCaseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cases/$caseId': typeof CasesCaseIdRouteWithChildren
  '/cases/$caseId/episodes/$episodeId': typeof CasesCaseIdEpisodesEpisodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cases/$caseId': typeof CasesCaseIdRouteWithChildren
  '/cases/$caseId/episodes/$episodeId': typeof CasesCaseIdEpisodesEpisodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cases/$caseId': typeof CasesCaseIdRouteWithChildren
  '/cases/$caseId/episodes/$episodeId': typeof CasesCaseIdEpisodesEpisodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cases/$caseId'
    | '/cases/$caseId/episodes/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/cases/$caseId' | '/cases/$caseId/episodes/$episodeId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cases/$caseId'
    | '/cases/$caseId/episodes/$episodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CasesCaseIdRoute: typeof CasesCaseIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId/episodes/$episodeId': {
      id: '/cases/$caseId/episodes/$episodeId'
      path: '/episodes/$episodeId'
      fullPath: '/cases/$caseId/episodes/$episodeId'
      preLoaderRoute: typeof CasesCaseIdEpisodesEpisodeIdRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
  }
}

interface CasesCaseIdRouteChildren {
  CasesCaseIdEpisodesEpisodeIdRoute: typeof CasesCaseIdEpisodesEpisodeIdRoute
}

const CasesCaseIdRouteChildren: CasesCaseIdRouteChildren = {
  CasesCaseIdEpisodesEpisodeIdRoute: CasesCaseIdEpisodesEpisodeIdRoute,
}

const CasesCaseIdRouteWithChildren = CasesCaseIdRoute._addFileChildren(
  CasesCaseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CasesCaseIdRoute: CasesCaseIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
