/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MapRouteImport } from './routes/map'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as CasesCaseIdIndexRouteImport } from './routes/cases.$caseId.index'
import { Route as CasesCaseIdEpisodesEpisodeIdRouteImport } from './routes/cases.$caseId.episodes.$episodeId'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdIndexRoute = CasesCaseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesCaseIdRoute,
} as any)
const CasesCaseIdEpisodesEpisodeIdRoute =
  CasesCaseIdEpisodesEpisodeIdRouteImport.update({
    id: '/episodes/$episodeId',
    path: '/episodes/$episodeId',
    getParentRoute: () => CasesCaseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/map': typeof MapRoute
  '/search': typeof SearchRoute
  '/timeline': typeof TimelineRoute
  '/cases/$caseId': typeof CasesCaseIdRouteWithChildren
  '/cases/$caseId/': typeof CasesCaseIdIndexRoute
  '/cases/$caseId/episodes/$episodeId': typeof CasesCaseIdEpisodesEpisodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/map': typeof MapRoute
  '/search': typeof SearchRoute
  '/timeline': typeof TimelineRoute
  '/cases/$caseId': typeof CasesCaseIdIndexRoute
  '/cases/$caseId/episodes/$episodeId': typeof CasesCaseIdEpisodesEpisodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/map': typeof MapRoute
  '/search': typeof SearchRoute
  '/timeline': typeof TimelineRoute
  '/cases/$caseId': typeof CasesCaseIdRouteWithChildren
  '/cases/$caseId/': typeof CasesCaseIdIndexRoute
  '/cases/$caseId/episodes/$episodeId': typeof CasesCaseIdEpisodesEpisodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/map'
    | '/search'
    | '/timeline'
    | '/cases/$caseId'
    | '/cases/$caseId/'
    | '/cases/$caseId/episodes/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/map'
    | '/search'
    | '/timeline'
    | '/cases/$caseId'
    | '/cases/$caseId/episodes/$episodeId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/map'
    | '/search'
    | '/timeline'
    | '/cases/$caseId'
    | '/cases/$caseId/'
    | '/cases/$caseId/episodes/$episodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MapRoute: typeof MapRoute
  SearchRoute: typeof SearchRoute
  TimelineRoute: typeof TimelineRoute
  CasesCaseIdRoute: typeof CasesCaseIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId/': {
      id: '/cases/$caseId/'
      path: '/'
      fullPath: '/cases/$caseId/'
      preLoaderRoute: typeof CasesCaseIdIndexRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
    '/cases/$caseId/episodes/$episodeId': {
      id: '/cases/$caseId/episodes/$episodeId'
      path: '/episodes/$episodeId'
      fullPath: '/cases/$caseId/episodes/$episodeId'
      preLoaderRoute: typeof CasesCaseIdEpisodesEpisodeIdRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
  }
}

interface CasesCaseIdRouteChildren {
  CasesCaseIdIndexRoute: typeof CasesCaseIdIndexRoute
  CasesCaseIdEpisodesEpisodeIdRoute: typeof CasesCaseIdEpisodesEpisodeIdRoute
}

const CasesCaseIdRouteChildren: CasesCaseIdRouteChildren = {
  CasesCaseIdIndexRoute: CasesCaseIdIndexRoute,
  CasesCaseIdEpisodesEpisodeIdRoute: CasesCaseIdEpisodesEpisodeIdRoute,
}

const CasesCaseIdRouteWithChildren = CasesCaseIdRoute._addFileChildren(
  CasesCaseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MapRoute: MapRoute,
  SearchRoute: SearchRoute,
  TimelineRoute: TimelineRoute,
  CasesCaseIdRoute: CasesCaseIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
